"""moment-pipeline — a DIMER pipeline for the pinned `AutonLab/MOMENT-1-base` checkpoint.

v1 exposes only what the pretrained base weights support: embeddings,
imputation/reconstruction, and reconstruction-based anomaly scoring.
Short-horizon forecasting is deliberately absent from the public API. Classification exists only
as the caller-trained adaptation contract in `adaptation` (a linear head over the pooled embeddings,
optionally with the last encoder blocks unfrozen), never as a pretrained head.
"""

from __future__ import annotations

from .adaptation import (
    ARTIFACT_FORMAT,
    DEFAULT_TRAINABLE_BLOCKS,
    ENCODER_BLOCKS,
    METRIC_DEFINITIONS,
    MIN_SCORED_RECORDS,
    POLICY_FROZEN,
    ClassifierAdapter,
    adapt,
    classification_metrics,
    classify,
    evaluate,
    features,
    knn_baseline,
    knn_predict,
    load_artifact,
    majority_baseline,
    save_artifact,
    windows_for,
)
from .anomaly import (
    ANOMALY_LOSSES,
    CHANNEL_AGGREGATIONS,
    AnomalyConfigError,
    AnomalyResult,
    aggregate_channels,
    residual,
    score_anomalies,
    score_from_reconstruction,
    top_k_recall,
)
from .canonical import WindowSet, expand_patch_view, to_patch_view, to_windows
from .config import (
    N_PATCHES,
    PATCH_LENGTH,
    PATCH_STRIDE,
    SEQUENCE_LENGTH,
    ConfigError,
    MomentConfig,
    ResourceLimits,
)
from .csvio import read_long_csv_bytes
from .embedding import EmbeddingResult, TaskMismatchError, embed
from .imputation import (
    DegenerateMaskError,
    ImputationMetrics,
    ReconstructionResult,
    impute,
    masked_point_metrics,
    reconstruct,
)
from .model import (
    DEFAULT_WEIGHTS_DIR,
    MANIFEST_NAME,
    MODEL_ID,
    MODEL_KEY,
    MODEL_LICENSE,
    MODEL_REVISION,
    PINNED_CONFIG_SHA256,
    PINNED_MODEL_ID,
    PINNED_REVISION,
    PINNED_WEIGHTS_BYTES,
    PINNED_WEIGHTS_SHA256,
    IntegrityError,
    LoadedMoment,
    ModelIdentity,
    ModelSourceError,
    VerifiedSnapshot,
    fetch_verified_snapshot,
    load_moment,
    stage_missing_files,
    verify_snapshot,
)
from .provenance import build_provenance
from .roles import INPUT_SCHEMA, evaluation_report, validate_inputs
from .samples import (
    ACTIVITIES,
    CHANNELS,
    CORPUS_BYTES,
    CORPUS_LICENSE,
    CORPUS_NAME,
    CORPUS_RELEASE,
    CORPUS_SHA256,
    CORPUS_URL,
    SAMPLE_SPLIT,
    WINDOW_LENGTH,
    build_sample_dataset,
    check_split_disjoint,
    class_names,
    dataset_digest,
    fetch_corpus,
    fetch_sample_dataset,
    load_byod_dataset,
    read_corpus,
    records_to_long_frame,
    split_dataset,
    user_summary,
    validate_dataset,
    window_digest,
    write_dataset_csv,
)
from .validation import ValidationError, ValidationReport, validate_long_frame

__version__ = "0.1.0"

__all__ = [
    "ACTIVITIES",
    "ANOMALY_LOSSES",
    "ARTIFACT_FORMAT",
    "AnomalyConfigError",
    "AnomalyResult",
    "CHANNELS",
    "CHANNEL_AGGREGATIONS",
    "CORPUS_BYTES",
    "CORPUS_LICENSE",
    "CORPUS_NAME",
    "CORPUS_RELEASE",
    "CORPUS_SHA256",
    "CORPUS_URL",
    "ClassifierAdapter",
    "ConfigError",
    "DEFAULT_TRAINABLE_BLOCKS",
    "DEFAULT_WEIGHTS_DIR",
    "DegenerateMaskError",
    "ENCODER_BLOCKS",
    "EmbeddingResult",
    "INPUT_SCHEMA",
    "ImputationMetrics",
    "IntegrityError",
    "LoadedMoment",
    "MANIFEST_NAME",
    "METRIC_DEFINITIONS",
    "MIN_SCORED_RECORDS",
    "MODEL_ID",
    "MODEL_KEY",
    "MODEL_LICENSE",
    "MODEL_REVISION",
    "ModelIdentity",
    "ModelSourceError",
    "MomentConfig",
    "N_PATCHES",
    "PATCH_LENGTH",
    "PATCH_STRIDE",
    "PINNED_CONFIG_SHA256",
    "PINNED_MODEL_ID",
    "PINNED_REVISION",
    "PINNED_WEIGHTS_BYTES",
    "PINNED_WEIGHTS_SHA256",
    "POLICY_FROZEN",
    "ReconstructionResult",
    "ResourceLimits",
    "SAMPLE_SPLIT",
    "SEQUENCE_LENGTH",
    "TaskMismatchError",
    "ValidationError",
    "ValidationReport",
    "VerifiedSnapshot",
    "WINDOW_LENGTH",
    "WindowSet",
    "__version__",
    "adapt",
    "aggregate_channels",
    "build_provenance",
    "build_sample_dataset",
    "check_split_disjoint",
    "class_names",
    "classification_metrics",
    "classify",
    "dataset_digest",
    "embed",
    "evaluate",
    "evaluation_report",
    "expand_patch_view",
    "features",
    "fetch_corpus",
    "fetch_sample_dataset",
    "fetch_verified_snapshot",
    "impute",
    "knn_baseline",
    "knn_predict",
    "load_artifact",
    "load_byod_dataset",
    "load_moment",
    "majority_baseline",
    "masked_point_metrics",
    "read_corpus",
    "read_long_csv_bytes",
    "reconstruct",
    "records_to_long_frame",
    "residual",
    "save_artifact",
    "score_anomalies",
    "score_from_reconstruction",
    "split_dataset",
    "stage_missing_files",
    "to_patch_view",
    "to_windows",
    "top_k_recall",
    "user_summary",
    "validate_dataset",
    "validate_inputs",
    "validate_long_frame",
    "verify_snapshot",
    "window_digest",
    "windows_for",
    "write_dataset_csv",
]
